### ISSUE TITLE
Schedule First Event

### ISSUE THREAD

**Issue by jthoms1** [nodeschool/madison#1]
Gather other mentors and sponsors for the first event.

**Comment by max-mapper** [comment]
cc @mikolalysenko

**Comment by mikolalysenko** [comment]
I could help out if there is something later on in October

**Comment by jthoms1** [comment]
Cool, I will be reaching out for more mentors at the upcoming MadJS meetup. http://www.meetup.com/MadisonJS/events/224875087/

**Comment by jthoms1** [comment]
Created a slack channel. https://nodeschoolmadison.slack.com

**Comment by mikolalysenko** [comment]
Great!  If you want any help, send me an invite.

**Comment by feltnerm** [comment]
Hey, I live in Madison. I'd like to help! Might be able to recruit some colleagues as well. :)

**Comment by jthoms1** [comment]
@feltnerm I will send you an invite to the slack channel.

**Comment by jthoms1** [comment]
We are now scheduled for the room at the central library.

**Room:** Meeting Room 301
**Date:** Thursday, December 03, 2015
**Time:** 6:00 PM to 8:45 PM

**Comment by jthoms1** [comment]
Mentors meeting Post MadJS meetup on November 9th. Please come by if you can make it or let me know if you want to be on the official list.
http://www.meetup.com/MadisonJS/events/225161004/

**Comment by zo0o0ot** [comment]
This issue can probably be closed.  The first event has happened, and the second event is scheduled for tomorrow (2/10/16).
I'm busy tomorrow, but I wanted to let you know that I'm willing to share some extra nodeschool Wisconsin stickers from the nodeschool Wisconsin group, if you're interested.

**Comment by jthoms1** [comment]
Good call, I will close this ticket. We also created alot of stickers for the Madison chapter.
