### ISSUE TITLE
June NodeSchool ideas

### ISSUE THREAD

**Issue by jthoms1** [nodeschool/madison#4]
Its that time again, hoping to get ideas on the next NodeSchool event.

**Comment by jazeee** [comment]
Based on the last meeting, I think that people were at various levels of advancement in the workshoppers. I think it makes sense, however, to keep moving forward.
I think the following would be fun to try, and people may find them applicable in their daily lives: `elementary-electron`, `promise-it-wont-hurt`, `test-anything`
(Note - I haven't looked at the actual workshopper for quality or content, ;> )

Perhaps we should send a survey out...
